# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  timeout: 5000
  username: pguser
  password: pguser

development:
  <<: *default
  database: pguser_development

test:
  <<: *default
  database: pguser_test

production:
  <<: *default
  database: postgres
  username: pguser
  password: 