
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: creditalert_development


test:
  <<: *default
  database: creditalert_test


production:
  <<: *default
  database: creditalert_production
  username: creditalert
  password: <%= ENV['CREDITALERT_DATABASE_PASSWORD'] %>
